services:
  ypb:
    image: ghcr.io/st0nie/ypb:master
    ports:
      - "3000:3000"
    volumes:
      - ./data:/var/lib/ypb
    command: [
      "ypb",
      "--file-path", "/var/lib/ypb",
      "--syntax-theme", "atom-one-dark"
    ]
    restart: unless-stopped